// Gimmy Gamming King - main interactions
const text=document.getElementById('text');const treeLeft=document.getElementById('tree-left');const treeRight=document.getElementById('tree-right');const gateLeft=document.getElementById('gate-left');const gateRight=document.getElementById('gate-right');
if(text&&treeLeft&&treeRight&&gateLeft&&gateRight){window.addEventListener('scroll',()=>{const value=window.scrollY;text.style.marginTop=`${value*2.5}px`;treeLeft.style.left=`${value*-1.5}px`;treeRight.style.left=`${value*1.5}px`;gateLeft.style.left=`${value*.5}px`;gateRight.style.left=`${value*-.5}px`},{passive:true})}
const menuToggle=document.querySelector('.menu-toggle');const navigation=document.querySelector('.navigation');
if(menuToggle&&navigation){menuToggle.addEventListener('click',()=>{const open=navigation.classList.toggle('open');menuToggle.setAttribute('aria-expanded',String(open));menuToggle.setAttribute('aria-label',open?'Close navigation menu':'Open navigation menu')});navigation.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{navigation.classList.remove('open');menuToggle.setAttribute('aria-expanded','false');menuToggle.setAttribute('aria-label','Open navigation menu')}));document.addEventListener('click',event=>{if(!navigation.contains(event.target)&&!menuToggle.contains(event.target)){navigation.classList.remove('open');menuToggle.setAttribute('aria-expanded','false')}})}
const slides=Array.from(document.querySelectorAll('.mySlides'));const dots=Array.from(document.querySelectorAll('.dot'));const thumbs=Array.from(document.querySelectorAll('.thumb'));const previousButton=document.querySelector('.prev');const nextButton=document.querySelector('.next');const playButton=document.querySelector('.gallery-play');const counter=document.getElementById('gallery-counter');const currentTitle=document.getElementById('gallery-title-current');const gallery=document.querySelector('.slideshow-container');const galleryNames=['Vblink','Medusa','CashFrenzy','GameVault','Juwa'];let slideIndex=0;let slideTimer=null;let playing=true;
function showSlide(index){if(!slides.length)return;slideIndex=(index+slides.length)%slides.length;slides.forEach((slide,i)=>slide.style.display=i===slideIndex?'block':'none');dots.forEach((dot,i)=>{dot.classList.toggle('active',i===slideIndex);dot.setAttribute('aria-current',i===slideIndex?'true':'false')});thumbs.forEach((thumb,i)=>{thumb.classList.toggle('active',i===slideIndex);thumb.setAttribute('aria-current',i===slideIndex?'true':'false')});if(counter)counter.textContent=`${slideIndex+1} / ${slides.length}`;if(currentTitle)currentTitle.textContent=galleryNames[slideIndex]||''}
function stopSlideshow(){if(slideTimer){clearInterval(slideTimer);slideTimer=null}}
function startSlideshow(){stopSlideshow();if(slides.length<2||!playing)return;slideTimer=setInterval(()=>showSlide(slideIndex+1),6000)}
function setSlide(index){showSlide(index);startSlideshow()}
if(slides.length){showSlide(0);startSlideshow();previousButton?.addEventListener('click',()=>setSlide(slideIndex-1));nextButton?.addEventListener('click',()=>setSlide(slideIndex+1));dots.forEach((dot,index)=>dot.addEventListener('click',()=>setSlide(index)));thumbs.forEach((thumb,index)=>thumb.addEventListener('click',()=>setSlide(index)));playButton?.addEventListener('click',()=>{playing=!playing;playButton.textContent=playing?'Ⅱ':'▶';playButton.setAttribute('aria-label',playing?'Pause automatic slideshow':'Play automatic slideshow');playButton.setAttribute('aria-pressed',String(playing));playing?startSlideshow():stopSlideshow()});gallery?.addEventListener('mouseenter',stopSlideshow);gallery?.addEventListener('mouseleave',startSlideshow);gallery?.addEventListener('focusin',stopSlideshow);gallery?.addEventListener('focusout',event=>{if(!gallery.contains(event.relatedTarget))startSlideshow()});document.addEventListener('keydown',event=>{if(!gallery||!gallery.matches(':focus-within'))return;if(event.key==='ArrowLeft')setSlide(slideIndex-1);if(event.key==='ArrowRight')setSlide(slideIndex+1);if(event.key===' '){event.preventDefault();playButton?.click()}})}
