// Gimmy Gamming King - main interactions
const text=document.getElementById('text'),treeLeft=document.getElementById('tree-left'),treeRight=document.getElementById('tree-right'),gateLeft=document.getElementById('gate-left'),gateRight=document.getElementById('gate-right');
if(text&&treeLeft&&treeRight&&gateLeft&&gateRight)window.addEventListener('scroll',()=>{const v=window.scrollY;text.style.marginTop=`${v*2.5}px`;treeLeft.style.left=`${v*-1.5}px`;treeRight.style.left=`${v*1.5}px`;gateLeft.style.left=`${v*.5}px`;gateRight.style.left=`${v*-.5}px`},{passive:true});
const menuToggle=document.querySelector('.menu-toggle'),navigation=document.querySelector('.navigation');
if(menuToggle&&navigation){menuToggle.addEventListener('click',()=>{const open=navigation.classList.toggle('open');menuToggle.setAttribute('aria-expanded',String(open));menuToggle.setAttribute('aria-label',open?'Close navigation menu':'Open navigation menu')});navigation.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{navigation.classList.remove('open');menuToggle.setAttribute('aria-expanded','false')}));document.addEventListener('click',e=>{if(!navigation.contains(e.target)&&!menuToggle.contains(e.target)){navigation.classList.remove('open');menuToggle.setAttribute('aria-expanded','false')}})}
const galleryMain=document.getElementById('gallery-main'),dotsBox=document.getElementById('gallery-dots'),thumbsBox=document.getElementById('gallery-thumbnails'),prev=document.querySelector('.prev'),next=document.querySelector('.next'),play=document.querySelector('.gallery-play'),counter=document.getElementById('gallery-counter'),title=document.getElementById('gallery-title-current'),gallery=document.querySelector('.slideshow-container');
let slides=[],dots=[],thumbs=[],index=0,timer=null,playing=true;
function imageTitle(file){return file.replace(/\.[^.]+$/,'').replace(/[-_]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function renderGallery(files){if(!galleryMain)return;files.forEach((file,i)=>{const name=imageTitle(file),slide=document.createElement('div');slide.className='mySlides fade';slide.innerHTML=`<img src="gallery/${encodeURIComponent(file)}" alt="${name} platform" loading="lazy">`;galleryMain.insertBefore(slide,prev);const dot=document.createElement('button');dot.className='dot';dot.type='button';dot.setAttribute('aria-label',`Show ${name}`);dot.addEventListener('click',()=>setSlide(i));dotsBox.appendChild(dot);const thumb=document.createElement('button');thumb.className='thumb';thumb.type='button';thumb.setAttribute('aria-label',`View ${name}`);thumb.innerHTML=`<img src="gallery/${encodeURIComponent(file)}" alt="">`;thumb.addEventListener('click',()=>setSlide(i));thumbsBox.appendChild(thumb)});slides=Array.from(galleryMain.querySelectorAll('.mySlides'));dots=Array.from(dotsBox.querySelectorAll('.dot'));thumbs=Array.from(thumbsBox.querySelectorAll('.thumb'));if(slides.length){showSlide(0);start()}else{counter.textContent='0 / 0';title.textContent='No images yet'}}
async function loadGallery(){try{const response=await fetch('https://api.github.com/repos/Kabikesu/Gkingeldorad.us/contents/gallery?ref=main',{headers:{Accept:'application/vnd.github+json'}});if(!response.ok)throw new Error('Gallery unavailable');const items=await response.json();const files=items.filter(x=>x.type==='file'&&/\.(jpe?g|png|webp|gif)$/i.test(x.name)).map(x=>x.name).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true,sensitivity:'base'}));renderGallery(files)}catch(error){counter.textContent='Gallery unavailable';title.textContent='Please try again later';console.error(error)}}
function showSlide(i){index=(i+slides.length)%slides.length;slides.forEach((s,n)=>s.style.display=n===index?'block':'none');dots.forEach((d,n)=>d.classList.toggle('active',n===index));thumbs.forEach((t,n)=>t.classList.toggle('active',n===index));counter.textContent=`${index+1} / ${slides.length}`;const img=slides[index]?.querySelector('img');title.textContent=img?.alt?.replace(/ platform$/i,'')||'Gallery'}
function stop(){clearInterval(timer);timer=null}function start(){stop();if(slides.length>1&&playing)timer=setInterval(()=>showSlide(index+1),6000)}function setSlide(i){showSlide(i);start()}
prev?.addEventListener('click',()=>setSlide(index-1));next?.addEventListener('click',()=>setSlide(index+1));play?.addEventListener('click',()=>{playing=!playing;play.textContent=playing?'Ⅱ':'▶';play.setAttribute('aria-label',playing?'Pause automatic slideshow':'Play automatic slideshow');play.setAttribute('aria-pressed',String(playing));playing?start():stop()});gallery?.addEventListener('mouseenter',stop);gallery?.addEventListener('mouseleave',start);gallery?.addEventListener('focusin',stop);gallery?.addEventListener('focusout',e=>{if(!gallery.contains(e.relatedTarget))start()});document.addEventListener('keydown',e=>{if(!gallery?.matches(':focus-within')||!slides.length)return;if(e.key==='ArrowLeft')setSlide(index-1);if(e.key==='ArrowRight')setSlide(index+1);if(e.key===' '){e.preventDefault();play?.click()}});loadGallery();
